apiVersion: v1
kind: Service
metadata:
  name: {{ include "pwa-weather.fullname" . }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
  labels:
{{ include "pwa-weather.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pwa-weather.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
