{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pwa-weather.serviceAccountName" . }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
  labels:
{{ include "pwa-weather.labels" . | indent 4 }}
{{- end -}}
