{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hello-world.serviceAccountName" . }}
  namespace: {{ required "namespace is missing" .Values.namespace }}
  labels:
{{ include "hello-world.labels" . | indent 4 }}
{{- end -}}
